### ISSUE TITLE
Expose new modes to HomeKit

### ISSUE THREAD

**Issue by nicoodeimos** [eibenp/homebridge-gree-airconditioner#1]
Hello there, I'd like to start by thanking you for this plugin! Amazing work.
I just installed a copy and it seems to work perfectly.

I was wondering if you were considering the following enhancements:
- Expose Fan and Dry modes as buttons
- Create an HTTP endpoint to update the displayed temp if AC units don't have an integrated sensor
- Expose Light switch to enable/disable LED display on units
- Allow hiding the additional Temperature accessory

Happy to help and test, if necessary!
Many thanks!

**Comment by eibenp** [comment]
Hello,

thank you for your suggestions!
I designed this plugin to be used from Apple's Home app and be as simple and clear as it can. So I do not plan to add buttons because they are confusing in the Home app. Some of your ideas may be implemented in a future release.

Kind regards

**Comment by nicoodeimos** [comment]
I see :( you could add them as secondary accessories though, « hidden » inside the main HeaterCooler accessory. 
I know the Home app is incomplete and lacks functionality, but your plugin is the only one working properly and it’s a shame that we cannot control the full spectrum of AC units just because Apple isn’t implementing everything.

Adding buttons nested in the main accessory (like you did for the Temp service) would allow to keep things clean and simple yet allowing to control what is not available in the main accessory. You could even add options to hide those buttons if necessary! 

Many thanks.

**Comment by eibenp** [comment]
Additional temperature sensor accessory configuration implemented in release v1.0.1.
Other suggested improvements are not planned in the near future.

**Comment by keness521** [comment]
I know the issue is closed, and this may not even be seen, but I would like to also vote for Fan and Dry mode options. I know none of them are "perfect" for HomeKit, but Fan and Dry are pretty integral modes of essentially ALL mini-splits. I use Fan mode, to keep air circulating, far more hours of the year than I do Cool or Heat.

There are several different ways to implement them, and for simplicity they can be optional and default to OFF, that's fine and that way doesn't clutter up anyone's Home app with anything they don't want.

My personal favorite is just to expose them as a separate service. Like homebridge-gree-heatercooler-v2 does it. That plugin had nearly nailed it, but had a few small bugs left and sadly seems to be abandoned when the author moved and no longer had a GREE AC anymore. (Oscillation was also quite convoluted with that plugin, so I don't use that function at all.)

**Comment by eibenp** [comment]
Maybe I will look for a solution but not in the near future. Currently it is not on my plan.
