### ISSUE TITLE
Incorrect display of current room temperature

### ISSUE THREAD

**Issue by Cd1905** [eibenp/homebridge-gree-airconditioner#22]
it works good but just Incorrect display of current room temperature.
           

            "name": "Gree",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": true,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 0,
            "defaultVerticalSwing": 0,
            "encryptionVersion": 0

**Comment by eibenp** [comment]
As described in plugin's documentation current room temperature display depends on the AC unit's capabilities and also the firmware version used. Some units does not have a built in sensor. Some others do have it but the firmware does not report the measured room temperature on the network. In both cases the plugin displays the actual target temperature in Home App instead of the measured one. Firmware problem can be solved by upgrading or downgrading the firmware to a version which does not miss room temperature measurement. (It depends on available firmware releases.) Finally the built in temperature sensor is not precise enough to display the real temperature. It can measure different values of the same room temperature in different modes of the unit (heating / cooling reports different values, although the room temperature is the same).
So in most cases incorrect display of room temperature depends on the AC unit, it's not a plugin problem.

Is this answer acceptable for you or you have a different problem? If not, please describe the problem in more details.

**Comment by Cd1905** [comment]
It was working before but now it is not working. I know there is a sensor in the air conditioner because it shows it on itself. The model is Gree Pulsar. There is a Xiaomi Air Cleaner air temperature and humidity sensor in the Apple Home Kit. Can't it take the value there as a basis for Gree?

**Comment by eibenp** [comment]
Unfortunately Apple Home Kit accessories can't communicate with each other. I think it's a security feature.
What does it mean exactly that temperature measurement is not working any more? Does anything changed in your environment? (E.g. updates installed) What is the problem? What do you see?

**Comment by Cd1905** [comment]
![Uploading IMG_3368.png…]()

**Comment by Cd1905** [comment]
![IMG_3368](https://github.com/user-attachments/assets/4d46f20e-07be-4a1b-9632-99932999ac17)

**Comment by eibenp** [comment]
Could you please set homebridge into debug mode (you can do it on settings page) and collect some logs about GREE plugin? I'd like to check the data received from your GREE unit.

**Comment by Cd1905** [comment]
now debug mode is opened i restarted homebridge. how can i collect logs? but i dont use gree now. i have gas boiller. When I increased the room temperature from 22 degrees to 24 degrees via the combi boiler, the instant temperature display on the Gree increased from 19 degrees to 21 degrees.

**Comment by eibenp** [comment]
If you use the UI of homebridge then you can see the logs on the status page but this contains only a few entries. Also there is a logs page accessible from the menu. On the logs page there is a download function also. If UI is not used then logs are available in file somewhere in your homebridge folder structure.

**Comment by Cd1905** [comment]
I would be glad if you could inform me when you work on this issue or if there is any update.

**Comment by eibenp** [comment]
> I would be glad if you could inform me when you work on this issue or if there is any update.

No problem, I can inform you, but without the logs I can't decide what should be fixed if any. Status updates are continuously reported in debug log also when the AC unit is turned off. So it can help me also in off mode.

**Comment by Cd1905** [comment]
okay just tell me what i should do for you .

**Comment by eibenp** [comment]
Just attach the collected debug logs to this issue

**Comment by Cd1905** [comment]
Is there any danger in sharing the logs with you? In terms of security and my personal information?

**Comment by eibenp** [comment]
GREE plugin logs do not contain any personal information. You can safely share them with me as others did before you in other issues. The logs contain information only about the AC unit and plugin working state.

**Comment by Cd1905** [comment]
I couldn't find exactly where it is. If you write in detail, I can do it. Is it the log title under the accessories?

**Comment by Cd1905** [comment]
![IMG_3370](https://github.com/user-attachments/assets/7f4fc0f8-290d-4504-95ce-ba3ad5d54dc6)

**Comment by eibenp** [comment]
yes, you are on the right way

**Comment by Cd1905** [comment]
[Uploading homebridge-gree-ac.log.txt…]()

**Comment by Cd1905** [comment]
[homebridge-gree-ac.log.txt](https://github.com/user-attachments/files/17848811/homebridge-gree-ac.log.txt)

**Comment by eibenp** [comment]
Thank You!
I have analyzed your logs. The GREE plugin works well. Your AC unit reports the 20 °C temperature value. The plugin doesn't need a fix.
If you think that the 20 °C value is not correct, because it should display 22 °C, then you can change the "sensorOffset" configuration parameter from 40 to 38. In this case the Home App will show +2 °C higher temperature than measured by the AC unit.
Unfortunately the GREE AC units do not have a good temperature sensor. The measured value is not precise and depends on many things. The unit can report different values about the same temperature if it is cooling or heating or turned off. A few degrees difference from the correct temperature is normal behavior. This is the reason why I have added the "sensorOffset" configuration parameter to the plugin. It helps to adjust the measured temperature value. I think that this poor quality built-in temperature sensor is one of the reasons why the official GREE+ mobile app does not support displaying the measured temperature at all.

**Comment by Cd1905** [comment]
thanks i chance value its works true now !

**Comment by Cd1905** [comment]
Sorry but the app started giving wrong information again. It shows 18 degrees when it is 22 degrees inside.

**Comment by eibenp** [comment]
Sorry but I can't fix it. It seems that the AC unit's built-in temperature sensor is malfunctioning and reports an invalid temperature on the network. Maybe a restart (removing power from the AC unit by unplugging it or using a hardware switch, and after a minute restoring power) can help, but I am not sure. The Home App displays exactly that temperature what is reported by the AC unit.

**Comment by Cd1905** [comment]
now i chance value ''29'' its works normal now. I'll try it for a few days. If it continues to work stably, I'll let you know.
