### ISSUE TITLE
Accessory is unsupported in the home app

### ISSUE THREAD

**Issue by Avigdorrr** [eibenp/homebridge-gree-airconditioner#23]
**Describe The Bug:**
When I add a new AC I see the accessory is unsupported in the home app

![IMG_6364](https://github.com/user-attachments/assets/90d6ed0b-8c7f-4e13-9d9a-b4d2119d19b2)

I tried to disable it by the config option and also to remove it from the config but it stayed like shown above no matter what I did

**To Reproduce:**
Add a new AC (model: tadiran alpha pro inverter 180)

**Expected behavior:**
See the AC in the app as a normal accessory.

**Logs:**

[homebridge-gree-ac.log 2.txt](https://github.com/user-attachments/files/17879294/homebridge-gree-ac.log.2.txt)

**Plugin Config:**

```json
            "name": "GREE Air Conditioner",
            "port": 7002,
            "scanInterval": 60,
            "devices": [
                {
                    "mac": "f4911e53a78f",
                    "name": "Guy's AC",
                    "model": "GWH09AAC-K3NN5A/I",
                    "speedSteps": 5,
                    "statusUpdateInterval": 1,
                    "sensorOffset": 40,
                    "minimumTargetTemperature": 16,
                    "maximumTargetTemperature": 30,
                    "xFanEnabled": true,
                    "temperatureSensor": "child",
                    "overrideDefaultVerticalSwing": 0,
                    "defaultVerticalSwing": 0,
                    "encryptionVersion": 0
                },
                {
                    "mac": "f4911e442a2e",
                    "name": "Maayan’s AC",
                    "model": "GWH09AAC-K3NN5A/I",
                    "speedSteps": 5,
                    "statusUpdateInterval": 1,
                    "sensorOffset": 40,
                    "minimumTargetTemperature": 16,
                    "maximumTargetTemperature": 30,
                    "xFanEnabled": true,
                    "temperatureSensor": "separate",
                    "overrideDefaultVerticalSwing": 0,
                    "defaultVerticalSwing": 0,
                    "encryptionVersion": 0
                },
                {
                    "mac": "502cc600a924",
                    "name": "Agam's AC",
                    "model": "GWH09QC-K3NNB4A/I",
                    "speedSteps": 5,
                    "statusUpdateInterval": 1,
                    "sensorOffset": 40,
                    "minimumTargetTemperature": 16,
                    "maximumTargetTemperature": 30,
                    "xFanEnabled": true,
                    "temperatureSensor": "separate",
                    "overrideDefaultVerticalSwing": 0,
                    "defaultVerticalSwing": 0,
                    "encryptionVersion": 0
                },
                {
                    "mac": "9424b8b5ab1f",
                    "name": "Gym AC",
                    "model": "GWH14QD-K3NNB4D/I",
                    "speedSteps": 5,
                    "statusUpdateInterval": 1,
                    "sensorOffset": 40,
                    "minimumTargetTemperature": 16,
                    "maximumTargetTemperature": 30,
                    "xFanEnabled": true,
                    "temperatureSensor": "separate",
                    "disabled": false,
                    "overrideDefaultVerticalSwing": 0,
                    "defaultVerticalSwing": 0,
                    "encryptionVersion": 0
                },
                {
                    "mac": "c0393707beb5",
                    "name": "Test AC",
                    "speedSteps": 5,
                    "statusUpdateInterval": 1,
                    "sensorOffset": 40,
                    "minimumTargetTemperature": 16,
                    "maximumTargetTemperature": 30,
                    "xFanEnabled": true,
                    "temperatureSensor": "separate",
                    "disabled": false,
                    "overrideDefaultVerticalSwing": 0,
                    "defaultVerticalSwing": 0,
                    "encryptionVersion": 0
                }
```

**Environment:**

* **Plugin Version**: 2.1.5
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 22.11.0
* **NPM Version**: 10.9.0
* **Operating System**: Debian

**Comment by eibenp** [comment]
Hi @Avigdorrr 
it seems it's a homebridge cache problem. I recommend you to reinstall the GREE plugin:

1. Uninstall the plugin
2. Remove all GREE accessories from the homebridge cache (see plugin documentation about details)
3. Install the latest version of the plugin
4. Add your accessories to homebridge

You need to restart homebridge several times during the above process.

**Comment by Avigdorrr** [comment]
Hi @eibenp 
I did all the things you said. but now I can't even see the accessory in homekit at all.
i have used the same configuration as above. here are the logs on debug mode but I couldn't even find any log about that spesific AC after i reinstalled the plugin
[homebridge-gree-ac.log (4).txt](https://github.com/user-attachments/files/17880085/homebridge-gree-ac.log.4.txt)

**Comment by eibenp** [comment]
Hi @Avigdorrr 
I don't see any problem in your logs. There are 3 accessories which are working well:
Guy's AC -- 10.100.102.24 -- f4911e53a78f
Agam's AC -- 10.100.102.25 -- 502cc600a924
Gym AC -- 10.100.102.182 -- 9424b8b5ab1f
In your configuration there is Maayan’s AC -- f4911e442a2e which is completely missing from the logs. It seems that it is defined but it hasn't work since 11/23/2024, 12:11:14 PM
Finally I see in your configuration a 5th accessory: Test AC -- c0393707beb5
It has been working in the first part of your logs as accessory:
Test AC -- 10.100.102.213 -- c0393707beb5
but it is not in your logs since 11/23/2024, 12:20:09 PM (It means that is has disappeared before you have reinstalled the plugin. The 3 accessories above did work at 11/23/2024, 12:22:33 PM also.)
I guess that you are looking for the Test AC. Missing log entries mean that this AC unit does not respond on the network at all. I know three cases when the AC unit sends no packets:

1. The AC unit doesn't work at all (no power or hardware failure)
2. Invalid network configuration of the AC unit (network is not configured or configured for a different network, in this case it should have 10.100.102.x address)
3. The AC unit is malfunctioning

I guess in our case the 3rd case is the most likely one. Sometimes AC unit stops responding on the network. In this case a restart solves the problem. Remove power from the unit (unplug or use a hardware switch), wait a minute and restore power. After that hopefully you can detect this unit on the network again.

**Comment by Avigdorrr** [comment]
@eibenp Thanks for the response.
I know Maayan's AC is off and that is because it got disconnected from the Gree app. so I expected it not to work.
After unplugging and plugging back again the Unit, the problem was solved exactly like you said, which is a bit weird because it worked perfectly on the Gree app even before the restart. Isn't it suppose to be not working even with the native app if the AC stops responding on the network?
anyway, thank you for your help, I appreciate your time and willingness to help 😁

**Comment by eibenp** [comment]
Hi @Avigdorrr 
You are welcome.
I have only theories about this problem because no public documentation is published by GREE. Homebridge support is based on reverse engineering. Network communication between any app and the GREE AC units is encrypted. When the plugin connects to the unit, it sends an init command to the unit which responds with a package which contains information about the unit and the encryption key. On homebridge restart the GREE plugin always sends this init command and binds only to devices which respond to the init command. This technique is used also for detecting network address changes. Maybe the official GREE+ mobile app sends this init command only once and it stores the encryption key. The plugin does not store the encryption key. I suppose that in your case the AC unit did not respond to the init command but it was able to communicate with apps which was already bound.  I think if you hadn't restarted the homebridge before, it would have been able to communicate with the AC unit for a while. I saw a similar issue several times before. Usually when this happens, later also the GREE+ app will become unresponsive. Missing response to the init command is only the first sign of a malfunctioning device. This problem was always solved by device power cycling. (At least which I have seen.) This is not user-friendly, but luckily it rarely happens.
